//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZJOASystem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZJOASystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批号.
        /// </summary>
        internal static string ACTION_BATCHNUMBER {
            get {
                return ResourceManager.GetString("ACTION_BATCHNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作说明.
        /// </summary>
        internal static string ACTION_COMMENTS {
            get {
                return ResourceManager.GetString("ACTION_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作员工.
        /// </summary>
        internal static string ACTION_EMPLOYEE {
            get {
                return ResourceManager.GetString("ACTION_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品编号.
        /// </summary>
        internal static string ACTION_NUMBER {
            get {
                return ResourceManager.GetString("ACTION_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 辨识码.
        /// </summary>
        internal static string ACTION_SERIALNUMBER {
            get {
                return ResourceManager.GetString("ACTION_SERIALNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作时间.
        /// </summary>
        internal static string ACTION_TIME {
            get {
                return ResourceManager.GetString("ACTION_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作类型.
        /// </summary>
        internal static string ACTION_TYPE {
            get {
                return ResourceManager.GetString("ACTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年份.
        /// </summary>
        internal static string ACTION_YEAR {
            get {
                return ResourceManager.GetString("ACTION_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发货地址.
        /// </summary>
        internal static string ADDITION_DEPARTURE {
            get {
                return ResourceManager.GetString("ADDITION_DEPARTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收货地址.
        /// </summary>
        internal static string ADDITION_DESTINATION {
            get {
                return ResourceManager.GetString("ADDITION_DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收货人.
        /// </summary>
        internal static string ADDITION_RECEIVER {
            get {
                return ResourceManager.GetString("ADDITION_RECEIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收货人电话.
        /// </summary>
        internal static string ADDITION_RECEIVERTELEPHONE {
            get {
                return ResourceManager.GetString("ADDITION_RECEIVERTELEPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发货人.
        /// </summary>
        internal static string ADDITION_SENDER {
            get {
                return ResourceManager.GetString("ADDITION_SENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发货人电话.
        /// </summary>
        internal static string ADDITION_SENDERTELEPHONE {
            get {
                return ResourceManager.GetString("ADDITION_SENDERTELEPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运单号.
        /// </summary>
        internal static string ADDITION_TRACKNUMBER {
            get {
                return ResourceManager.GetString("ADDITION_TRACKNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 紫珺办公系统.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回产品清单.
        /// </summary>
        internal static string BACKTO_PRODUCTLIST {
            get {
                return ResourceManager.GetString("BACKTO_PRODUCTLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览.
        /// </summary>
        internal static string BROWSEFILE {
            get {
                return ResourceManager.GetString("BROWSEFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -&gt;.
        /// </summary>
        internal static string BUTTON_MOVELEFT {
            get {
                return ResourceManager.GetString("BUTTON_MOVELEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;-.
        /// </summary>
        internal static string BUTTON_MOVERIGHT {
            get {
                return ResourceManager.GetString("BUTTON_MOVERIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消上传.
        /// </summary>
        internal static string CANCELUPLOAD {
            get {
                return ResourceManager.GetString("CANCELUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请从列表中选择操作员工（可多选）：.
        /// </summary>
        internal static string CHOOSE_PRODUCT_ACTIONERS {
            get {
                return ResourceManager.GetString("CHOOSE_PRODUCT_ACTIONERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入产品批号：.
        /// </summary>
        internal static string CHOOSE_PRODUCT_BATCH {
            get {
                return ResourceManager.GetString("CHOOSE_PRODUCT_BATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入产品描述信息（非必需）：.
        /// </summary>
        internal static string CHOOSE_PRODUCT_DESCRIPTION {
            get {
                return ResourceManager.GetString("CHOOSE_PRODUCT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入产品名称：.
        /// </summary>
        internal static string CHOOSE_PRODUCT_NAME {
            get {
                return ResourceManager.GetString("CHOOSE_PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入产品标识码：.
        /// </summary>
        internal static string CHOOSE_PRODUCT_SERIAL {
            get {
                return ResourceManager.GetString("CHOOSE_PRODUCT_SERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择要组装的产品.
        /// </summary>
        internal static string CHOOSE_PRODUCT_SETUP {
            get {
                return ResourceManager.GetString("CHOOSE_PRODUCT_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择产品年份：.
        /// </summary>
        internal static string CHOOSE_PRODUCT_YEARNUMBER {
            get {
                return ResourceManager.GetString("CHOOSE_PRODUCT_YEARNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择要制造的产品名类：.
        /// </summary>
        internal static string CHOOSE_PRODUCTBASE_LIST {
            get {
                return ResourceManager.GetString("CHOOSE_PRODUCTBASE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        internal static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注.
        /// </summary>
        internal static string COMMENTS {
            get {
                return ResourceManager.GetString("COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建.
        /// </summary>
        internal static string CREATE {
            get {
                return ResourceManager.GetString("CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认删除？.
        /// </summary>
        internal static string DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部门.
        /// </summary>
        internal static string DEPARTMENT {
            get {
                return ResourceManager.GetString("DEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建部门记录.
        /// </summary>
        internal static string DEPARTMENT_CREATE {
            get {
                return ResourceManager.GetString("DEPARTMENT_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部门经理.
        /// </summary>
        internal static string DEPARTMENT_MANAGER {
            get {
                return ResourceManager.GetString("DEPARTMENT_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部门名称.
        /// </summary>
        internal static string DEPARTMENT_NAME {
            get {
                return ResourceManager.GetString("DEPARTMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (无).
        /// </summary>
        internal static string DEPARTMENT_NONE {
            get {
                return ResourceManager.GetString("DEPARTMENT_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上级部门.
        /// </summary>
        internal static string DEPARTMENT_PARENT_NAME {
            get {
                return ResourceManager.GetString("DEPARTMENT_PARENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回部门列表.
        /// </summary>
        internal static string DEPARTMENT_RETURNLIST {
            get {
                return ResourceManager.GetString("DEPARTMENT_RETURNLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部门管理.
        /// </summary>
        internal static string DEPARTMENT_TITLE {
            get {
                return ResourceManager.GetString("DEPARTMENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属部门.
        /// </summary>
        internal static string DEPARTMENTLIST {
            get {
                return ResourceManager.GetString("DEPARTMENTLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 详情.
        /// </summary>
        internal static string DETAIL {
            get {
                return ResourceManager.GetString("DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改.
        /// </summary>
        internal static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 员工.
        /// </summary>
        internal static string EMPLOYEE {
            get {
                return ResourceManager.GetString("EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建员工记录.
        /// </summary>
        internal static string EMPLOYEE_CREATE {
            get {
                return ResourceManager.GetString("EMPLOYEE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电子邮件.
        /// </summary>
        internal static string EMPLOYEE_EMAIL {
            get {
                return ResourceManager.GetString("EMPLOYEE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        internal static string EMPLOYEE_NAME {
            get {
                return ResourceManager.GetString("EMPLOYEE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回员工列表.
        /// </summary>
        internal static string EMPLOYEE_RETURNLIST {
            get {
                return ResourceManager.GetString("EMPLOYEE_RETURNLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联系电话.
        /// </summary>
        internal static string EMPLOYEE_TELEPHONE {
            get {
                return ResourceManager.GetString("EMPLOYEE_TELEPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 员工管理.
        /// </summary>
        internal static string EMPLOYEE_TITLE {
            get {
                return ResourceManager.GetString("EMPLOYEE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主页.
        /// </summary>
        internal static string HOME_TITLE {
            get {
                return ResourceManager.GetString("HOME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        internal static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出系统.
        /// </summary>
        internal static string LOGOFF {
            get {
                return ResourceManager.GetString("LOGOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品操作记录.
        /// </summary>
        internal static string PRODUCT_ACTIONLIST {
            get {
                return ResourceManager.GetString("PRODUCT_ACTIONLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 制造.
        /// </summary>
        internal static string PRODUCT_CREATE {
            get {
                return ResourceManager.GetString("PRODUCT_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发货.
        /// </summary>
        internal static string PRODUCT_DELIEVER {
            get {
                return ResourceManager.GetString("PRODUCT_DELIEVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描述.
        /// </summary>
        internal static string PRODUCT_DESCRIPTION {
            get {
                return ResourceManager.GetString("PRODUCT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品明细.
        /// </summary>
        internal static string PRODUCT_DETAIL_LIST {
            get {
                return ResourceManager.GetString("PRODUCT_DETAIL_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编码.
        /// </summary>
        internal static string PRODUCT_ENCODE {
            get {
                return ResourceManager.GetString("PRODUCT_ENCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出产品清单.
        /// </summary>
        internal static string PRODUCT_EXPORT {
            get {
                return ResourceManager.GetString("PRODUCT_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 维修.
        /// </summary>
        internal static string PRODUCT_FIX {
            get {
                return ResourceManager.GetString("PRODUCT_FIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入产品清单.
        /// </summary>
        internal static string PRODUCT_IMPORT {
            get {
                return ResourceManager.GetString("PRODUCT_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传产品清单文件.
        /// </summary>
        internal static string PRODUCT_IMPORT_UPLOAD {
            get {
                return ResourceManager.GetString("PRODUCT_IMPORT_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清单.
        /// </summary>
        internal static string PRODUCT_LIST {
            get {
                return ResourceManager.GetString("PRODUCT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品名称.
        /// </summary>
        internal static string PRODUCT_NAME {
            get {
                return ResourceManager.GetString("PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编号.
        /// </summary>
        internal static string PRODUCT_NUMBER {
            get {
                return ResourceManager.GetString("PRODUCT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装箱.
        /// </summary>
        internal static string PRODUCT_PACKAGE {
            get {
                return ResourceManager.GetString("PRODUCT_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打印产品.
        /// </summary>
        internal static string PRODUCT_PRINT {
            get {
                return ResourceManager.GetString("PRODUCT_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组装.
        /// </summary>
        internal static string PRODUCT_SETUP {
            get {
                return ResourceManager.GetString("PRODUCT_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态.
        /// </summary>
        internal static string PRODUCT_STATUS {
            get {
                return ResourceManager.GetString("PRODUCT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测.
        /// </summary>
        internal static string PRODUCT_TEST {
            get {
                return ResourceManager.GetString("PRODUCT_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品管理.
        /// </summary>
        internal static string PRODUCT_TITLE {
            get {
                return ResourceManager.GetString("PRODUCT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品目录.
        /// </summary>
        internal static string PRODUCTBASE_LIST {
            get {
                return ResourceManager.GetString("PRODUCTBASE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        internal static string REGISTER {
            get {
                return ResourceManager.GetString("REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已发货.
        /// </summary>
        internal static string STATUS_DELIEVERED {
            get {
                return ResourceManager.GetString("STATUS_DELIEVERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不可用.
        /// </summary>
        internal static string STATUS_DISABLED {
            get {
                return ResourceManager.GetString("STATUS_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已修复.
        /// </summary>
        internal static string STATUS_FIXED {
            get {
                return ResourceManager.GetString("STATUS_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已装箱.
        /// </summary>
        internal static string STATUS_PACKAGE {
            get {
                return ResourceManager.GetString("STATUS_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测通过.
        /// </summary>
        internal static string STATUS_QUALIFIED {
            get {
                return ResourceManager.GetString("STATUS_QUALIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测未通过.
        /// </summary>
        internal static string STATUS_UNQUALIFIED {
            get {
                return ResourceManager.GetString("STATUS_UNQUALIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交.
        /// </summary>
        internal static string SUBMIT {
            get {
                return ResourceManager.GetString("SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传.
        /// </summary>
        internal static string UPLOADFILE {
            get {
                return ResourceManager.GetString("UPLOADFILE", resourceCulture);
            }
        }
    }
}
