//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36392
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZJOASystem.OAService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OAService.OAServiceSoap")]
    public interface OAServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ZJOASystem.OAService.HelloWorldResponse HelloWorld(ZJOASystem.OAService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ZJOASystem.OAService.HelloWorldResponse> HelloWorldAsync(ZJOASystem.OAService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetDepartmentsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartments", ReplyAction="*")]
        ZJOASystem.OAService.GetDepartmentsResponse GetDepartments(ZJOASystem.OAService.GetDepartmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartments", ReplyAction="*")]
        System.Threading.Tasks.Task<ZJOASystem.OAService.GetDepartmentsResponse> GetDepartmentsAsync(ZJOASystem.OAService.GetDepartmentsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ZJOASystem.OAService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ZJOASystem.OAService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZJOASystem.OAService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ZJOASystem.OAService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepartments", Namespace="http://tempuri.org/", Order=0)]
        public ZJOASystem.OAService.GetDepartmentsRequestBody Body;
        
        public GetDepartmentsRequest() {
        }
        
        public GetDepartmentsRequest(ZJOASystem.OAService.GetDepartmentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDepartmentsRequestBody {
        
        public GetDepartmentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepartmentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZJOASystem.OAService.GetDepartmentsResponseBody Body;
        
        public GetDepartmentsResponse() {
        }
        
        public GetDepartmentsResponse(ZJOASystem.OAService.GetDepartmentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDepartmentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDepartmentsResult;
        
        public GetDepartmentsResponseBody() {
        }
        
        public GetDepartmentsResponseBody(string GetDepartmentsResult) {
            this.GetDepartmentsResult = GetDepartmentsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OAServiceSoapChannel : ZJOASystem.OAService.OAServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OAServiceSoapClient : System.ServiceModel.ClientBase<ZJOASystem.OAService.OAServiceSoap>, ZJOASystem.OAService.OAServiceSoap {
        
        public OAServiceSoapClient() {
        }
        
        public OAServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OAServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OAServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OAServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZJOASystem.OAService.HelloWorldResponse ZJOASystem.OAService.OAServiceSoap.HelloWorld(ZJOASystem.OAService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ZJOASystem.OAService.HelloWorldRequest inValue = new ZJOASystem.OAService.HelloWorldRequest();
            inValue.Body = new ZJOASystem.OAService.HelloWorldRequestBody();
            ZJOASystem.OAService.HelloWorldResponse retVal = ((ZJOASystem.OAService.OAServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZJOASystem.OAService.HelloWorldResponse> ZJOASystem.OAService.OAServiceSoap.HelloWorldAsync(ZJOASystem.OAService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZJOASystem.OAService.HelloWorldResponse> HelloWorldAsync() {
            ZJOASystem.OAService.HelloWorldRequest inValue = new ZJOASystem.OAService.HelloWorldRequest();
            inValue.Body = new ZJOASystem.OAService.HelloWorldRequestBody();
            return ((ZJOASystem.OAService.OAServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZJOASystem.OAService.GetDepartmentsResponse ZJOASystem.OAService.OAServiceSoap.GetDepartments(ZJOASystem.OAService.GetDepartmentsRequest request) {
            return base.Channel.GetDepartments(request);
        }
        
        public string GetDepartments() {
            ZJOASystem.OAService.GetDepartmentsRequest inValue = new ZJOASystem.OAService.GetDepartmentsRequest();
            inValue.Body = new ZJOASystem.OAService.GetDepartmentsRequestBody();
            ZJOASystem.OAService.GetDepartmentsResponse retVal = ((ZJOASystem.OAService.OAServiceSoap)(this)).GetDepartments(inValue);
            return retVal.Body.GetDepartmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZJOASystem.OAService.GetDepartmentsResponse> ZJOASystem.OAService.OAServiceSoap.GetDepartmentsAsync(ZJOASystem.OAService.GetDepartmentsRequest request) {
            return base.Channel.GetDepartmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZJOASystem.OAService.GetDepartmentsResponse> GetDepartmentsAsync() {
            ZJOASystem.OAService.GetDepartmentsRequest inValue = new ZJOASystem.OAService.GetDepartmentsRequest();
            inValue.Body = new ZJOASystem.OAService.GetDepartmentsRequestBody();
            return ((ZJOASystem.OAService.OAServiceSoap)(this)).GetDepartmentsAsync(inValue);
        }
    }
}
